version: "3.9"

services:
  saloonbook-ws:
    container_name: saloonbook-ws
    platform: linux/arm64/v8 
    build:
      context: ./SaloonBook-WS
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - saloonbook-db
    environment:
      - "ConnectionStrings:DefaultConnection=Host=saloonbook-db:5432;Username=postgres;Password=postgres;Database=saloon-book"

  saloonbook-db:
    container_name: saloonbook-db
    image: "postgres:15.3-bullseye"
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "5445:5432"
    volumes:
      - saloonbook-db-postgres-volume:/var/lib/postgresql/data

volumes:
  saloonbook-db-postgres-volume:
